version: 2

models:
  - name: dostievski_info
    description: "dbt model containing the information from the google sheet"
    columns:
      - name: 'id'
        type: 'numeric'
      - name: 'category'
        type: 'string'
      - name: 'title'
        type: 'string'
      - name: 'yop'
        type: 'date'
      - name: 'descr'
        type: 'string'
    tests:
      - unique
      - not_null