# profiles.yml

bigquery_profile:
  target: ${{ secrets.DBT_TARGET }}
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dostoievski-project
      dataset: dostoievsky_db
      threads: 1
      timeout_seconds: 300
      keyfile: ${{ secrets.DBT_GCP_KEYFILE }}
      location: US